# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.common.by import By
import pytest
from TestTool.control import *
from TestTool.task import *
from TestTool.init import *

from TestTool.test_case.create_site import *
import sys
import unittest
import os
class TestDemotest():
  def setup_method(self):
    self.vars={}
    init_log("/Users/yu-sung/Documents/ci/gmn-1.0.46-autotesting/selenium/test-case/selenium.log",logging.INFO)
    
    start_test(os.path.basename(__file__))
    read_config(self,"../config.ini")
    try:
      self.driver = init_driver(self)
      self.driver.implicitly_wait(10)
    except:
      logging.error('Prepare webdriver error', exc_info=True)

  def teardown_method(self):
    self.driver.quit()

  def test_create_site(self):
    assert create_site_goto(self) == True

    for count in range (1,2):
      assert create_site_create(self) == True
      time.sleep(10)
      error_count=0
      for i in range(1,8):
        result=create_site_check(self)      
        error_count=i
        logging.info('Check time= %s',i)
        if result == True:
          logging.info('CheckSuccess time= %s',i)
          error_count=0
          break
        time.sleep(10)
      assert error_count==0
      assert create_site_delete(self) == True
      logging.info("#########Create site success times= %s", count)
