# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.common.by import By
import pytest
from TestTool.control import *
from TestTool.task import *
from TestTool.init import *
from TestTool.test_case.sa_test import*
class TestDemotest():
  def setup_method(self, method):

    self.vars={}
    read_config(self,"../config.ini")
    try:
      self.driver = init_driver(self)
      self.driver.implicitly_wait(10)
    except:
      logging.error('Prepare webdriver error', exc_info=True)

  def teardown_method(self):
    self.driver.quit()

  def test_django(self):
      print (self.driver.get(self.vars["url"]))
      time.sleep(3)
      assert get_text(self,By.XPATH,"/html/body/nav/div/a","test ui") != ""
      time.sleep(1)
      assert get_text(self,By.XPATH,"/html/body/nav/div/div/ul/li[1]/a","test1 ui") != ""
      time.sleep(1)
      assert get_text(self,By.XPATH,"/html/body/nav/div/div/ul/li[2]/a","test2 ui") != ""
      time.sleep(1)
      assert get_text(self,By.XPATH,"/html/body/nav/div/div/ul/li[3]/a","test3 ui") != ""
      time.sleep(1)
      assert get_text(self,By.XPATH,"/html/body/nav/div/div/ul/li[4]/a","test4 ui") != ""
      time.sleep(1)

      print ("Test success")





