# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.common.by import By
import pytest
from TestTool.control import *
from TestTool.task import *
from TestTool.init import *
from TestTool.test_case.sa_test import*
class TestDemotest():
  def setup_method(self, method):

    self.vars={}
    init_log("./selenium.log",logging.INFO)
    start_test(os.path.basename(__file__))
    read_config(self,"../config.ini")
    try:
      self.driver = init_driver(self)
      self.driver.implicitly_wait(10)
    except:
      logging.error('Prepare webdriver error', exc_info=True)

  def teardown_method(self):
    self.driver.quit()

  def test_sa_0001_1_1(self):
    sa_0001_1_1_check(self)


