# Generated by Selenium IDE
import pytest
import time
import json
import logging
import os
import configparser
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from TestTool.init import *
from TestTool.control import *
from TestTool.task import *
class SeleniumTest():
  def setup_method(self):
    init_log("selenium.log",logging.INFO)
    start_test(os.path.basename(__file__))
    self.vars={}
    read_config(self,"../config.ini")

    try:
      self.driver = init_driver(self)
    except:
      logging.error('Prepare webdriver error', exc_info=True)
      self.driver.quit()
  
  def teardown_method(self):
    end_test(os.path.basename(__file__))
    self.driver.quit()

  def SA_0026(self):
    connect_web(self)
    login_web(self,self.vars["account_user"][0],self.vars["account_password"][0])
    click_button(self,By.XPATH,"//li[4]/span/span","Projects","Click project button")
    
    delete_status=False
    for project in self.vars["project_name"]:
      if delete_project(self,project) == True:
        delete_status = True
    if delete_status == True:
      click_button(self,By.XPATH,"//button/span/i","","Delete project")
      time.sleep(3)
      self.driver.refresh()
      time.sleep(5)

    project_dict={}
    for i in range(1, 50, 1):
      user_target = "//tr[%d]/td[2]/span" % (i)
      username=(get_text(self,By.XPATH,user_target,"Get project name"))
      logging.info(username)
      project_dict[username]=username
      if username =="":
        break

    error=False
    for project in self.vars["project_name"]:
      try:
        if project_dict[project] != "":
          error=True
          self.driver.quit()
          raise "Delete project error"
      except:
        if error==True:          
          logging.info("Delete project %s error ",project)
          print(project_dict["error_message"])
          self.driver.quit()
          
  
    logging.info("Delete project success")
      
if __name__ == "__main__":
  driver = SeleniumTest()
  driver.setup_method()
  driver.SA_0026()
  driver.teardown_method()