# Generated by Selenium IDE
import pytest
import time
import json
import logging
import os
import configparser
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from TestTool.init import *
from TestTool.control import *
from TestTool.task import *
class SeleniumTest():
  def setup_method(self):
    init_log("selenium.log",logging.INFO)
    start_test(os.path.basename(__file__))
    self.vars={}
    read_config(self,"../config.ini")

    try:
      self.driver = init_driver(self)
    except:
      logging.error('Prepare webdriver error', exc_info=True)
      self.driver.quit()
  def teardown_method(self):
    end_test(os.path.basename(__file__))
    self.driver.quit()
  def SA_0017(self):
    connect_web(self)
    login_web(self,self.vars["account_user"][0],self.vars["account_password"][0])
    # Check login  
    check_text(self,By.XPATH,"//div[4]/button/span/span[2]",self.vars["account_user"][0],"check login")
    # Check login  
    check_text(self,By.XPATH,"//div[4]/button/span/span[2]",self.vars["account_user"][0],"check login")   
    
    check_text(self,By.XPATH,"//li[3]/div/span/span","Users","check Users")
    click_button(self,By.XPATH,"//li[3]/div/span/span","Users","click Users")
    
    check_text(self,By.XPATH,"//li[3]/ul/li/span/span","User Management","check User Management")
    click_button(self,By.XPATH,"//li[3]/ul/li/span/span","User Management","check User Management")
    
    for val in self.vars["account_user"]:
        if val == "admin":
          continue
        create_user(self,val,val)

    time.sleep(3)
    try:
      logging.info("scroll to mid")
      scroll_down="document.evaluate('/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/div[2]', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scroll(0,%s)" % ("10000")
      get_scroll_height="return document.evaluate('/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/div[2]', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scrollTop"
      self.driver.execute_script(scroll_down)
      scroll_height=int(self.driver.execute_script(get_scroll_height))
      scroll_down_mid="return document.evaluate('/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/div[2]', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scroll(0,%s)" % (scroll_height/2)
      self.driver.execute_script(scroll_down_mid)
    except:
      logging.error("scroll error")

    account_user_dict = {}
    for i in range(2, 50, 1):
      user_target = "//tr[%d]/td[3]/span/a" % (i)
      username=(get_text(self,By.XPATH,user_target,"get User Management "))
      
      email_target = "//tr[%d]/td[4]/span" % (i)
      email=(get_text(self,By.XPATH,email_target,"get User Management "))
      
      logging.info('get user name = %s',username)
      logging.info('get user email = %s',email)
      if username=="":
        break
      account_user_dict[username]=email

    for host in self.vars["account_user"]:
      try:
        if host == "admin":
          continue
      except:
        logging.error('user not found = %s',host)
        self.driver.quit()

if __name__ == "__main__":
  driver = SeleniumTest()
  driver.setup_method()
  driver.SA_0017()
  driver.teardown_method()